### ISSUE TITLE
Coding and Pull requests

### ISSUE THREAD

**Issue by ellentkoch** [UBC-MDS/DSCI_532_group-106_supermarket#21]
Ensure everyone is getting a chance to code and submit pull requests. There are large differences in the numbers of lines of code between contributors. @clsu22 @moniquewong @reikookamoto

**Comment by moniquewong** [comment]
@ellentkoch  - we have this same issue again for milestone 2 because we uploaded our Jupyter notebook files to share code. @reikookamoto started the initial version which led to a lot of lines of code uploaded by Reiko. We all had a chance to code the .py files in this milestone which is not reflected in the analytics because of the Jupyter notebook code.
